config/routes.rb
Rails.application.routes.draw do

  root to:'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'admin', to: 'admin/homes#top'
  get 'my_page', to: 'public/homes#my_page'
  get 'recipes/index_all', to: 'public/recipes#index_all'
  delete 'purchas_recipes/destroy_all', to: 'public/purchas_recipes#destroy_all'
  delete 'purchas_foods/destroy_all', to: 'public/purchas_foods#destroy_all'


  namespace :admin do
    resources :foods, except: [:show,:new]
    resources :food_genres, except: [:edit,:new,:show]
    resources :recipe_genres, except: [:edit,:new,:show]
  end

  scope module: "public" do
    resources :recipes do
      resources :recipe_foods, only: [:index, :new, :create, :update, :destroy]
    end
    resources :purchas_recipes, except: [:new, :show]

    resources :purchas_foods, except: [:new, :show]
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes
  has_many :purchas_recipes
  has_many :purchas_foods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :food_genre
  has_many :recipe_foods
  has_many :recipes, through: :recipes_foods
  has_many :purchas_foods
  enum status: { integer: 0, fraction: 1, string: 2 }
end

app/models/food_genre.rb
class FoodGenre < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :recipe_foods, through: :foods
  has_many :purchas_foods, through: :foods
end

app/models/purchas_food.rb
class PurchasFood < ApplicationRecord
  belongs_to :end_user
  belongs_to :food

  def division
    numerator/denominator
  end

  def remainder
    numerator%denominator
  end
end

app/models/purchas_recipe.rb
class PurchasRecipe < ApplicationRecord
  validates :amount, :numericality => { :greater_than => 0 }
  belongs_to :end_user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :end_user
  belongs_to :recipe_genre
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  has_many :purchas_recipes
  attachment :image
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def division
    numerator/denominator
  end

  def remainder
    numerator%denominator
  end
end

app/models/recipe_genre.rb
class RecipeGenre < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @food = Food.new
    @food_genres = FoodGenre.includes(:foods).all
  end

  def create
    @food = Food.new(food_params)
    @food.save
    redirect_to admin_foods_path
  end

  def edit
    @food = Food.find(params[:id])
    @food_genres = FoodGenre.includes(:foods).all
  end

  def update
    @food = Food.find(params[:id])
    @food.update(food_params)
    redirect_to admin_foods_path
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to admin_foods_path
  end

  private
  def food_params
    params.require(:food).permit(:food_genre_id, :name, :unit, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when EndUser
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when EndUser, :end_user, :end_users
      root_path
    when Admin, :admin, :admins
      new_admin_session_path
    end
  end
end

app/helpers/admin/admin_foods_helper.rb
module Admin::AdminFoodsHelper
end

app/helpers/admin/food_genres_helper.rb
module Admin::FoodGenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipe_genres_helper.rb
module Admin::RecipeGenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchas_recipes_helper.rb
module PurchasRecipesHelper
end

app/helpers/recipe_genres_helper.rb
module RecipeGenresHelper
end

app/views/admin/foods/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= link_to "食材ジャンル", admin_food_genres_path %>
      <h3>編集</h3>
      <%= form_with model: @food, url: admin_food_path(@food), local: true do |f| %>
        <%= f.collection_select :food_genre_id, @food_genres, :id, :name %>
        食品名
        <%= f.text_field :name %>
        単位
        <%= f.text_field :unit %>
        <%= f.select :status, Food.statuses.keys.map {|k| [I18n.t("enums.food.status.#{k}"), k]} %>
        <%= f.submit '更新', class:"btn btn-primary" %>
      <% end %>
      <%= link_to '削除', admin_food_path(@food), method: :delete, class:"btn btn-danger", "data-confirm" => "本当に削除しますか？" %>

      <% @food_genres.each do |food_genre| %>
        </BR>
        <%= food_genre.name %>
        </BR>
        <% if food_genre.status == true %>
          買い物リスト(表示)
        <% else %>
          買い物リスト(非表示)
        <% end %>
          <% food_genre.foods.each do |food|%>
            <%= food.name %>
            <%= link_to edit_admin_food_path(food) do %>
              X
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/foods/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-10 mx-auto"><%= link_to "食材ジャンル", admin_food_genres_path,class:"btn btn-success btn-sm" %></div>
  </div>
  <div class="row mt-3">
    <div class="col-10 mx-auto">
      <%= form_with model: @food, url: admin_foods_path, local: true do |f| %>
        <%= f.collection_select :food_genre_id, @food_genres, :id, :name, { prompt: "選択してください" } %>
        食品名
        <%= f.text_field :name %>
        単位
        <%= f.text_field :unit %>
        <%= f.select :status, Food.statuses.keys.map {|k| [I18n.t("enums.food.status.#{k}"), k]} %>
        <%= f.submit '追加', class:"btn btn-primary" %>
      <% end %>
      <table class="table table-responsive mt-3">
      <% @food_genres.each do |food_genre| %>
        <thead>
          <tr>
            <th><%= food_genre.name %></th>
            <th class="py-2">
              <%= form_with model: @food, url: admin_foods_path,class:'inline', local: true do |f| %>
                <%= f.hidden_field :food_genre_id, :value => food_genre.id %>
                食品名
                <%= f.text_field :name %>
                単位
                <%= f.text_field :unit %>
                <%= f.select :status, Food.statuses.keys.map {|k| [I18n.t("enums.food.status.#{k}"), k]} %>
                <%= f.submit '追加', class:"btn btn-primary btn-sm" %>
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-1" colspan="2">
              <% food_genre.foods.each do |food|%>
                <%= food.name %>
                <%= link_to edit_admin_food_path(food) do %>
                  X
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>