config/routes.rb
Rails.application.routes.draw do

  root to:'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'admin', to: 'admin/homes#top'
  get 'my_page', to: 'public/homes#my_page'
  get 'recipes/index_all', to: 'public/recipes#index_all'
  delete 'purchas_recipes/destroy_all', to: 'public/purchas_recipes#destroy_all'
  delete 'purchas_foods/destroy_all', to: 'public/purchas_foods#destroy_all'


  namespace :admin do
    resources :foods, except: [:show,:new]
    resources :food_genres, except: [:edit,:new,:show]
    resources :recipe_genres, except: [:edit,:new,:show]
  end

  scope module: "public" do
    resources :recipes do
      resources :recipe_foods, only: [:index, :new, :create, :update, :destroy]
    end
    resources :purchas_recipes, except: [:new, :show]

    resources :purchas_foods, except: [:new, :show]
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes
  has_many :purchas_recipes
  has_many :purchas_foods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :food_genre
  has_many :recipe_foods
  has_many :recipes, through: :recipes_foods
  has_many :purchas_foods
  enum status: { integer: 0, fraction: 1, string: 2 }
end

app/models/food_genre.rb
class FoodGenre < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :recipe_foods, through: :foods
  has_many :purchas_foods, through: :foods
end

app/models/purchas_food.rb
class PurchasFood < ApplicationRecord
  belongs_to :end_user
  belongs_to :food

  def division
    numerator/denominator
  end

  def remainder
    numerator%denominator
  end
end

app/models/purchas_recipe.rb
class PurchasRecipe < ApplicationRecord
  validates :amount, :numericality => { :greater_than => 0 }
  belongs_to :end_user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :end_user
  belongs_to :recipe_genre
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  has_many :purchas_recipes
  attachment :image
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def division
    numerator/denominator
  end

  def remainder
    numerator%denominator
  end
end

app/models/recipe_genre.rb
class RecipeGenre < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @food = Food.new
    @food_genres = FoodGenre.includes(:foods).all
  end

  def create
    @food = Food.new(food_params)
    @food.save
    redirect_to admin_foods_path
  end

  def edit
    @food = Food.find(params[:id])
    @food_genres = FoodGenre.includes(:foods).all
  end

  def update
    @food = Food.find(params[:id])
    @food.update(food_params)
    redirect_to admin_foods_path
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to admin_foods_path
  end

  private
  def food_params
    params.require(:food).permit(:food_genre_id, :name, :unit, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when EndUser
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when EndUser, :end_user, :end_users
      root_path
    when Admin, :admin, :admins
      new_admin_session_path
    end
  end
end

app/helpers/admin/admin_foods_helper.rb
module Admin::AdminFoodsHelper
end

app/helpers/admin/food_genres_helper.rb
module Admin::FoodGenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipe_genres_helper.rb
module Admin::RecipeGenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchas_recipes_helper.rb
module PurchasRecipesHelper
end

app/helpers/recipe_genres_helper.rb
module RecipeGenresHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenuShopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark nav-font">
      <div class="container">
        <div class="navbar-brand nav-font"><%= link_to 'Menu&Shopping', root_path, class:"text-light mr-3 nav-font" %></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon bg"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if admin_signed_in? %>
              <li class="nav-item"><%= link_to 'みんなのレシピ', recipes_index_all_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to '食材一覧', admin_foods_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'レシピジャンル', admin_recipe_genres_path, class:"nav-link text-light" %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'みんなのレシピ', recipes_index_all_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'マイレシピ', recipes_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'レシピを書く', new_recipe_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to '献立リスト', purchas_recipes_path, class:"nav-link text-light" %></li>
            <% end %>
          </ul>

          <ul class="navbar-nav">
            <% if end_user_signed_in? %>
              <li class="nav-item"><%= link_to 'マイページ', my_page_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_end_user_session_path, method: :delete, class:"nav-link text-light" %></li>
            <% elsif admin_signed_in? %>
              <li class="nav-item"><%= link_to '管理者画面', admin_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"nav-link text-light" %></li>
            <% else %>
              <li class="nav-item"><%= link_to '新規登録', new_end_user_registration_path, class:"nav-link text-light" %></li>
              <li class="nav-item"><%= link_to 'ログイン', new_end_user_session_path, class:"nav-link text-light" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <footer class="footer bg-light">
      <div class="container">
        <p class="text-muted float-right pt-2">Copyright(C) Menu&Shopping.</p>
      </div>
    </footer>
  </body>
</html>